#?? ?? ??? ??? ??? ? ?? ??? ??? ????? ???? ??
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #h2 : ??? ??
  h2:
    console:
      enabled: true
      path: /h2-console
#jpa : h2?? ??? ??? ???? ?????? ??? ? ???? ???? ?? ??
#springboot 2.5 ???? defer- ??? ???? ???? ?? ?? ???? ???
jpa:
  defer-datasource-initialization: true
  database-platform: H2
  hibernate:
    ddl-auto: create-drop
  open-in-view: false
  properties:
    hibernate:
    format_sql: true
    show_sql: true